// src/game/main.cpp — Phase 2 worker w1 (game core).
//
// Host entry point for the Mischief Makers static recomp. Wires the translated
// game (mm_recompiled) to the librecomp/ultramodern runtime via
// `recomp::start(Configuration)`, modeled on
// reference/Zelda64Recomp/src/main/main.cpp.
//
// CALLBACK SEAMS — real implementations come from the component libraries:
//
//   rsp callbacks    -> mm_rsp (src/rsp/): recompiled aspMain audio ucode;
//                       gfx tasks (gspFast3D) go to the renderer, not the RSP
//   audio callbacks  -> mm_audio_input (src/audio_input/): SDL2 queue device
//   input callbacks  -> mm_audio_input: SDL2 keyboard + game controller
//   renderer + gfx   -> STUBBED until src/graphics/ lands (RT64); the stub
//                       renderer reports valid()==false so the gfx thread
//                       aborts cleanly instead of crashing
//   events/error/threads -> optional, stay stubbed
//
// Remaining stub groups live in mm::stub::* namespaces so the graphics
// component can drop in without touching anything else. See PHASE2_NOTES_w1.md.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <string>
#include <string_view>
#include <memory>
#include <vector>

#define SDL_MAIN_HANDLED
#include <SDL2/SDL.h>

#include "ultramodern/ultra64.h"
#include "ultramodern/ultramodern.hpp"
#include "librecomp/game.hpp"
#include "librecomp/overlays.hpp"
#include "recomp.h"

#include "mm_rsp.hpp"
#include "mm_audio_input.hpp"
#ifdef MM_HAS_GRAPHICS
#include "mm_graphics.h"
#endif

// Generated by N64Recomp into the mm_recompiled library (lookup.cpp +
// funcs_60.c). Declared here so we don't have to pull funcs.h (megabytes of
// prototypes) into this TU.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
extern gpr get_entrypoint_address();
extern const char* get_rom_name();

// Phase 2 overlay registration + host function entries
// (register_overlays.cpp, same target).
namespace troublemakers {
void register_overlays();
void on_game_init(uint8_t* rdram, recomp_context* ctx);
}

// ============================================================================
// Stub seams. Each namespace below is one replaceable callback group.
// ============================================================================

// ----------------------------------------------------------------------------
// SEAM (graphics worker): the renderer. The real implementation returns an
// RT64-backed RendererContext. This stub returns a context whose valid() is
// false, so the gfx thread aborts cleanly at startup (see
// ultramodern/src/events.cpp gfx_thread_func) instead of crashing.
// ----------------------------------------------------------------------------
class StubRendererContext : public ultramodern::renderer::RendererContext {
  public:
    bool valid() override { return false; }
    bool update_config(const ultramodern::renderer::GraphicsConfig&,
                       const ultramodern::renderer::GraphicsConfig&) override { return false; }
    void enable_instant_present() override {}
    void send_dl(const OSTask*) override {}
    void update_screen() override {}
    void shutdown() override {}
    uint32_t get_display_framerate() const override { return 60; }
    float get_resolution_scale() const override { return 1.0f; }
};

namespace mm::stub::gfx {
// SEAM (graphics worker owns the real window). For bring-up we create a real
// SDL window so the stretch run gets as far as window creation.
ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER) < 0) {
        std::fprintf(stderr, "Failed to initialize SDL2: %s\n", SDL_GetError());
    }
    return nullptr;
}

ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    SDL_Window* win = SDL_CreateWindow(
        "Mischief Makers: Recompiled",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        640, 480, SDL_WINDOW_RESIZABLE);
    if (win == nullptr) {
        std::fprintf(stderr, "Failed to create window: %s\n", SDL_GetError());
    }
    return ultramodern::renderer::WindowHandle{win};
}

void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    // Drain SDL events so the OS/window manager stays responsive and so closing
    // the window cleanly shuts the runtime down.
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        if (ev.type == SDL_QUIT) {
            ultramodern::quit();
        }
    }
}
} // namespace mm::stub::gfx

namespace mm::stub::renderer {
// SEAM (graphics worker): create the real RT64 render context.
std::unique_ptr<ultramodern::renderer::RendererContext>
create_render_context(uint8_t* /*rdram*/, ultramodern::renderer::WindowHandle /*window_handle*/, bool /*developer_mode*/) {
    std::fprintf(stderr, "[stub] create_render_context: no real renderer (RT64) yet — "
                         "gfx thread will abort cleanly.\n");
    return std::make_unique<StubRendererContext>();
}
} // namespace mm::stub::renderer

// Set in main() once a ROM has been validated; consumed by gfx_init_callback
// to auto-start the game (the reference triggers start_game from its launcher
// UI, which this project doesn't have yet).
static bool g_rom_selected = false;
static const std::u8string kGameId = u8"troublemakers.n64.us.1";

namespace mm::stub::events {
// Auto-start trigger. The reference starts the game from its launcher UI,
// long after the runtime is idling; we have no UI yet, so start from the VI
// tick instead. It must NOT happen before the first tick: update_vi
// dereferences ViState::mode unconditionally, and that pointer is only seeded
// by set_dummy_vi, which runs on VI ticks while the game is NOT yet started.
// Starting from the end of a tick guarantees the mode is seeded (it persists
// through the per-tick state swaps thereafter).
void vi_callback() {
    static bool started = false;
    if (g_rom_selected && !started) {
        started = true;
        recomp::start_game(kGameId);
    }
}
// Runs once the gfx thread has created the renderer; nothing to do here.
void gfx_init_callback() {}
} // namespace mm::stub::events

namespace mm::stub::error {
// SEAM (optional). OS error dialog.
void message_box(const char* msg) {
    std::fprintf(stderr, "[recomp error] %s\n", msg);
}
} // namespace mm::stub::error

namespace mm::stub::threads {
// SEAM (optional). Debug thread names.
std::string get_game_thread_name(const OSThread* /*t*/) { return "[Game]"; }
} // namespace mm::stub::threads

// ---------------------------------------------------------------------------
// The single supported game entry. rom_hash is XXH3-64 of the whole ROM
// (matches librecomp's check_hash); computed from baserom.us1.z64.
// Entry address 0x80000400 comes from RecompiledFuncs/lookup.cpp.
// ---------------------------------------------------------------------------
static std::vector<recomp::GameEntry> supported_games() {
    return {
        {
            .rom_hash = 0xECB515AE2C898E4FULL,
            .internal_name = "MISCHIEF MAKERS",
            .game_id = kGameId,
            .mod_game_id = "troublemakers",
            .save_type = mm_audio_input::save_type(), // Eep4k; evidence in PHASE2_NOTES_w4.md
            .is_enabled = true,
            .decompression_routine = nullptr,
            .has_compressed_code = false,
            .entrypoint_address = get_entrypoint_address(),
            .entrypoint = recomp_entrypoint,
            .on_init_callback = troublemakers::on_game_init,
        },
    };
}

static void exit_error(const char* str) {
    std::fprintf(stderr, "%s\n", str);
    std::exit(EXIT_FAILURE);
}

int main(int argc, char** argv) {
    recomp::Version project_version{};
    if (!recomp::Version::from_string("0.2.0", project_version)) {
        exit_error("Invalid version string");
    }

    // Store config (mods, saves) under a per-project folder in the user's
    // config dir. Sibling workers may relocate this.
    namespace fs = std::filesystem;
    fs::path config_dir = fs::path(getenv("HOME") ? getenv("HOME") : ".") / ".config" / "troublemakers-recomp";
    std::error_code ec;
    fs::create_directories(config_dir, ec);
    mm_audio_input::register_save_config(config_dir); // recomp::register_config_path
    mm_audio_input::init(); // SDL audio device + game-controller subsystem

    // Register the supported game + overlay/section tables.
    for (const auto& game : supported_games()) {
        recomp::register_game(game);
    }
    troublemakers::register_overlays();

    // Optional: if a ROM path is given as argv[1], validate + load it now so
    // the stretch run can prove the hash/name/save wiring without the launcher
    // UI. (The game is NOT auto-started; that needs the real RSP/renderer.)
    if (argc >= 2) {
        // select_rom validates the ROM against the registered GameEntry keyed
        // by game_id, so we must name the game we registered above.
        std::u8string game_id = kGameId;
        auto err = recomp::select_rom(fs::path(argv[1]), game_id);
        const char* msg = nullptr;
        switch (err) {
            case recomp::RomValidationError::Good: msg = "ROM validated and loaded."; break;
            case recomp::RomValidationError::FailedToOpen: msg = "ROM: failed to open."; break;
            case recomp::RomValidationError::NotARom: msg = "ROM: not a ROM."; break;
            case recomp::RomValidationError::IncorrectRom: msg = "ROM: incorrect ROM (hash mismatch)."; break;
            case recomp::RomValidationError::IncorrectVersion: msg = "ROM: incorrect version."; break;
            case recomp::RomValidationError::NotYet: msg = "ROM: not yet supported."; break;
            default: msg = "ROM: other error."; break;
        }
        std::fprintf(stdout, "[recomp] %s\n", msg);
        if (err != recomp::RomValidationError::Good) {
            return EXIT_FAILURE;
        }
        g_rom_selected = true; // gfx_init_callback starts the game once gfx is up
    }

    // Build the runtime configuration. RSP + audio + input come from the
    // component libraries; renderer/gfx stay stubbed until src/graphics/ (RT64)
    // lands. rsp_callbacks and renderer_callbacks are mandatory (librecomp
    // asserts they are non-empty).
    recomp::rsp::callbacks_t rsp_callbacks = mm_rsp::make_callbacks();

    ultramodern::renderer::callbacks_t renderer_callbacks{
#ifdef MM_HAS_GRAPHICS
        .create_render_context = mm::graphics::create_render_context,
#else
        .create_render_context = mm::stub::renderer::create_render_context,
#endif
    };

    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = mm::stub::gfx::create_gfx,
        .create_window = mm::stub::gfx::create_window,
        .update_gfx = mm::stub::gfx::update_gfx,
    };

    ultramodern::audio_callbacks_t audio_callbacks = mm_audio_input::audio_callbacks();

    ultramodern::input::callbacks_t input_callbacks = mm_audio_input::input_callbacks();

    ultramodern::events::callbacks_t events_callbacks{
        .vi_callback = mm::stub::events::vi_callback,
        .gfx_init_callback = mm::stub::events::gfx_init_callback,
    };

    ultramodern::error_handling::callbacks_t error_handling_callbacks{
        .message_box = mm::stub::error::message_box,
    };

    ultramodern::threads::callbacks_t threads_callbacks{
        .get_game_thread_name = mm::stub::threads::get_game_thread_name,
    };

    recomp::Configuration cfg{
        .project_version = project_version,
        .window_handle = {}, // default -> create_window is called
        .rsp_callbacks = rsp_callbacks,
        .renderer_callbacks = renderer_callbacks,
        .audio_callbacks = audio_callbacks,
        .input_callbacks = input_callbacks,
        .gfx_callbacks = gfx_callbacks,
        .events_callbacks = events_callbacks,
        .error_handling_callbacks = error_handling_callbacks,
        .threads_callbacks = threads_callbacks,
        .message_queue_control = {},
    };

    // Blocks until the runtime quits (window close via update_gfx above, or
    // ultramodern::quit() from elsewhere).
    recomp::start(cfg);

    return EXIT_SUCCESS;
}
