// src/game/main.cpp — Phase 2 worker w1 (game core).
//
// Host entry point for Trouble Makers (Mischief Makers recompilation). Wires the translated
// game (mm_recompiled) to the librecomp/ultramodern runtime via
// `recomp::start(Configuration)`, modeled on
// reference/Zelda64Recomp/src/main/main.cpp.
//
// CALLBACK SEAMS — real implementations come from the component libraries:
//
//   rsp callbacks    -> mm_rsp (src/rsp/): recompiled aspMain audio ucode;
//                       gfx tasks (gspFast3D) go to the renderer, not the RSP
//   audio callbacks  -> mm_audio_input (src/audio_input/): SDL2 queue device
//   input callbacks  -> mm_audio_input: SDL2 keyboard + game controller
//   renderer + gfx   -> STUBBED until src/graphics/ lands (RT64); the stub
//                       renderer reports valid()==false so the gfx thread
//                       aborts cleanly instead of crashing
//   events/error/threads -> optional, stay stubbed
//
// Remaining stub groups live in mm::stub::* namespaces so the graphics
// component can drop in without touching anything else. See PHASE2_NOTES_w1.md.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <memory>
#include <vector>

#define SDL_MAIN_HANDLED
#include <SDL2/SDL.h>
#if defined(_WIN32)
#include <SDL2/SDL_syswm.h> // HWND extraction for WindowHandle
#endif

#include "ultramodern/ultra64.h"
#include "ultramodern/ultramodern.hpp"
#include "librecomp/game.hpp"
#include "librecomp/overlays.hpp"
#include "recomp.h"

#include "app_dirs.h"
#include "mm_rsp.hpp"
#include "mm_audio_input.hpp"
#ifdef MM_HAS_GRAPHICS
#include "mm_graphics.h"
#include "launcher.h"
#endif

// Generated by N64Recomp into the mm_recompiled library (lookup.cpp +
// funcs_60.c). Declared here so we don't have to pull funcs.h (megabytes of
// prototypes) into this TU.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
extern gpr get_entrypoint_address();
extern const char* get_rom_name();

// Phase 2 overlay registration + host function entries
// (register_overlays.cpp, same target).
namespace troublemakers {
void register_overlays();
void on_game_init(uint8_t* rdram, recomp_context* ctx);
}

// ============================================================================
// Stub seams. Each namespace below is one replaceable callback group.
// ============================================================================

// ----------------------------------------------------------------------------
// SEAM (graphics worker): the renderer. The real implementation returns an
// RT64-backed RendererContext. This stub returns a context whose valid() is
// false, so the gfx thread aborts cleanly at startup (see
// ultramodern/src/events.cpp gfx_thread_func) instead of crashing.
// ----------------------------------------------------------------------------
class StubRendererContext : public ultramodern::renderer::RendererContext {
  public:
    // MM_HEADLESS_GFX=1 makes the stub renderer report valid, so the gfx
    // thread's action loop runs (send_dl no-ops, dp_complete still fires)
    // and the game's full frame loop executes with no renderer or display —
    // the harness for headless testing with -DMM_BUILD_GRAPHICS=OFF.
    bool valid() override { return getenv("MM_HEADLESS_GFX") != nullptr; }
    bool update_config(const ultramodern::renderer::GraphicsConfig&,
                       const ultramodern::renderer::GraphicsConfig&) override { return false; }
    void enable_instant_present() override {}
    // Counted + flushed so headless fps is measurable from a redirected log
    // (stderr is block-buffered off a tty, and the run ends in abort(), which
    // does not flush stdio buffers — fflush keeps every counted line). Mirrors
    // the [gfx] send_dl counter in rt64_render_context.cpp (TEMP DIAGNOSTIC).
    void send_dl(const OSTask*) override {
        static uint64_t n = 0;
        if (n < 3 || n % 10 == 0) {
            std::fprintf(stderr, "[gfx] send_dl #%llu\n", (unsigned long long)n);
            std::fflush(stderr);
        }
        n++;
    }
    void update_screen() override {}
    void shutdown() override {}
    uint32_t get_display_framerate() const override { return 60; }
    float get_resolution_scale() const override { return 1.0f; }
};

// Display options: loaded from the config file, overridden by the command
// line in main(), toggleable at runtime (F11). The internal render
// resolution is RT64's job: with Resolution::Auto the scene rasterizes at
// window-integer-scale (a 4K window ≈ 9x native), so a bigger window IS
// higher resolution. ds_option supersamples on top (SSAA).
static int g_window_w = 1280;
static int g_window_h = 960;
static bool g_fullscreen = false;
static bool g_widescreen = false;
static int g_ssaa = 1;
static int g_msaa = 0;
// Remembered ROM path (UTF-8), so the launcher can offer "Start Game"
// immediately on the next run. Empty until a ROM validates.
static std::string g_rom_path;
static SDL_Window* g_sdl_window = nullptr;

// Build the renderer config from the globals. Safe to call at runtime too:
// trigger_config_action() makes the gfx thread hand old/new configs to
// RendererContext::update_config.
static void apply_display_config() {
    ultramodern::renderer::GraphicsConfig cfg{};
    cfg.res_option = ultramodern::renderer::Resolution::Auto; // window-integer-scale
    cfg.wm_option = g_fullscreen ? ultramodern::renderer::WindowMode::Fullscreen
                                 : ultramodern::renderer::WindowMode::Windowed;
    // Expand lets RT64 widen the rendered field to the window's aspect;
    // Original letterboxes to the game's 4:3. Widescreen on a 2D game can
    // reveal areas the artists never meant to be seen — it's opt-in.
    cfg.ar_option = g_widescreen ? ultramodern::renderer::AspectRatio::Expand
                                 : ultramodern::renderer::AspectRatio::Original;
    cfg.msaa_option = g_msaa == 2 ? ultramodern::renderer::Antialiasing::MSAA2X
                    : g_msaa == 4 ? ultramodern::renderer::Antialiasing::MSAA4X
                    : g_msaa == 8 ? ultramodern::renderer::Antialiasing::MSAA8X
                                  : ultramodern::renderer::Antialiasing::None;
    cfg.rr_option = ultramodern::renderer::RefreshRate::Original; // natively 60Hz
    cfg.hpfb_option = ultramodern::renderer::HighPrecisionFramebuffer::Auto;
    cfg.ds_option = g_ssaa;
    ultramodern::renderer::set_graphics_config(cfg);
}

// Persist display options across runs: a tiny key=value file next to the
// saves. CLI flags override the file; runtime toggles write it back.
// fstream (not fopen) because filesystem::path::c_str() is wchar_t* on
// Windows; the stream constructors take the path directly on any platform.
static std::filesystem::path display_cfg_path() {
    return mm::get_app_folder_path() / "display.cfg";
}

static void load_display_config() {
    std::ifstream f(display_cfg_path());
    if (!f.is_open()) return;
    std::string line;
    while (std::getline(f, line)) {
        size_t eq = line.find('=');
        if (eq == std::string::npos) continue;
        std::string_view k = std::string_view(line).substr(0, eq);
        std::string v = line.substr(eq + 1);
        if (!v.empty() && v.back() == '\r') v.pop_back(); // tolerate CRLF
        if (k == "rom") {
            g_rom_path = v; // UTF-8 path; may legitimately contain spaces
            continue;
        }
        int value = std::atoi(v.c_str());
        if (k == "window_w" && value >= 320) g_window_w = value;
        else if (k == "window_h" && value >= 240) g_window_h = value;
        else if (k == "fullscreen") g_fullscreen = value != 0;
        else if (k == "widescreen") g_widescreen = value != 0;
        else if (k == "ssaa" && value >= 1 && value <= 8) g_ssaa = value;
        else if (k == "msaa" && (value == 0 || value == 2 || value == 4 || value == 8)) g_msaa = value;
    }
}

static void save_display_config() {
    std::error_code ec;
    std::filesystem::create_directories(display_cfg_path().parent_path(), ec);
    std::ofstream f(display_cfg_path(), std::ios::trunc);
    if (!f.is_open()) return;
    f << "window_w=" << g_window_w << "\nwindow_h=" << g_window_h
      << "\nfullscreen=" << (g_fullscreen ? 1 : 0)
      << "\nwidescreen=" << (g_widescreen ? 1 : 0)
      << "\nssaa=" << g_ssaa << "\nmsaa=" << g_msaa << "\n";
    if (!g_rom_path.empty()) {
        f << "rom=" << g_rom_path << "\n";
    }
}

namespace mm::stub::gfx {
// SEAM (graphics worker owns the real window). For bring-up we create a real
// SDL window so the stretch run gets as far as window creation.
ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    // Windows-only hint, added in SDL 2.24 — absent from older SDL2 headers
    // (Ubuntu 22.04 ships 2.0.20), and hint macros are #defines, so guard it.
#ifdef SDL_HINT_WINDOWS_DPI_AWARENESS
    SDL_SetHint(SDL_HINT_WINDOWS_DPI_AWARENESS, "permonitorv2");
#endif
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER) < 0) {
        std::fprintf(stderr, "Failed to initialize SDL2: %s\n", SDL_GetError());
    }
    return nullptr;
}

ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    // MM_WIN_POS="x,y" pins the window at a fixed desktop position, and
    // MM_DISPLAY=<index> centers it on a specific display (debug: keeps the
    // game on one monitor so external captures — incl. fullscreen — land on
    // the intended screen instead of a compositor-chosen one).
    int pos_x = SDL_WINDOWPOS_CENTERED, pos_y = SDL_WINDOWPOS_CENTERED;
    if (const char* di = getenv("MM_DISPLAY")) {
        int idx = std::atoi(di);
        pos_x = SDL_WINDOWPOS_CENTERED_DISPLAY(idx);
        pos_y = SDL_WINDOWPOS_CENTERED_DISPLAY(idx);
    }
    if (const char* wp = getenv("MM_WIN_POS")) {
        int px, py;
        if (std::sscanf(wp, "%d,%d", &px, &py) == 2) { pos_x = px; pos_y = py; }
    }
    SDL_Window* win = SDL_CreateWindow(
        "Trouble Makers",
        pos_x, pos_y,
        g_window_w, g_window_h, SDL_WINDOW_RESIZABLE);
    if (win == nullptr) {
        std::fprintf(stderr, "Failed to create window: %s\n", SDL_GetError());
    }
    // RT64 also honors WindowMode::Fullscreen from the graphics config at
    // context creation; setting the SDL flag here just avoids a visible
    // windowed->fullscreen flip at startup.
    if (g_fullscreen) {
        SDL_SetWindowFullscreen(win, SDL_WINDOW_FULLSCREEN_DESKTOP);
    }
    g_sdl_window = win;
    // WindowHandle is platform-specific (renderer_context.hpp): HWND+thread
    // on Windows, SDL_Window* on Linux. Same extraction as the reference.
#if defined(_WIN32)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    SDL_GetWindowWMInfo(win, &wm_info);
    return ultramodern::renderer::WindowHandle{wm_info.info.win.window, GetCurrentThreadId()};
#else
    return ultramodern::renderer::WindowHandle{win};
#endif
}

void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    // Drain SDL events so the OS/window manager stays responsive and so closing
    // the window cleanly shuts the runtime down. Hotkeys:
    //   F11        toggle fullscreen (persisted)
    //   Tab (hold) fast-forward 3x (game speed via the VI/timer multiplier)
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        if (ev.type == SDL_QUIT) {
            ultramodern::quit();
        } else if (ev.type == SDL_KEYDOWN && ev.key.repeat == 0) {
            if (ev.key.keysym.scancode == SDL_SCANCODE_F11 && g_sdl_window != nullptr) {
                g_fullscreen = !g_fullscreen;
                SDL_SetWindowFullscreen(g_sdl_window,
                    g_fullscreen ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0);
                apply_display_config();
                ultramodern::trigger_config_action();
                save_display_config();
            } else if (ev.key.keysym.scancode == SDL_SCANCODE_TAB) {
                ultramodern::set_speed_multiplier(3);
            }
        } else if (ev.type == SDL_KEYUP && ev.key.keysym.scancode == SDL_SCANCODE_TAB) {
            ultramodern::set_speed_multiplier(1);
        }
    }
}
} // namespace mm::stub::gfx

namespace mm::stub::renderer {
// SEAM (graphics worker): create the real RT64 render context.
std::unique_ptr<ultramodern::renderer::RendererContext>
create_render_context(uint8_t* /*rdram*/, ultramodern::renderer::WindowHandle /*window_handle*/, bool /*developer_mode*/) {
    std::fprintf(stderr, "[stub] create_render_context: no real renderer (RT64) yet — "
                         "gfx thread will abort cleanly.\n");
    return std::make_unique<StubRendererContext>();
}
} // namespace mm::stub::renderer

// Set in main() once a ROM has been validated; consumed by gfx_init_callback
// to auto-start the game (the reference triggers start_game from its launcher
// UI, which this project doesn't have yet).
static bool g_rom_selected = false;
static const std::u8string kGameId = u8"troublemakers.n64.us.1";

namespace mm::stub::events {
// Auto-start trigger. The reference starts the game from its launcher UI,
// long after the runtime is idling; we have no UI yet, so start from the VI
// tick instead. It must NOT happen before the first tick: update_vi
// dereferences ViState::mode unconditionally, and that pointer is only seeded
// by set_dummy_vi, which runs on VI ticks while the game is NOT yet started.
// Starting from the end of a tick guarantees the mode is seeded (it persists
// through the per-tick state swaps thereafter).
void vi_callback() {
    static bool started = false;
    if (g_rom_selected && !started) {
        started = true;
        recomp::start_game(kGameId);
    }
}
// Runs once the gfx thread has created the renderer; nothing to do here.
void gfx_init_callback() {}
} // namespace mm::stub::events

namespace mm::stub::error {
// SEAM (optional). OS error dialog.
void message_box(const char* msg) {
    std::fprintf(stderr, "[recomp error] %s\n", msg);
}
} // namespace mm::stub::error

namespace mm::stub::threads {
// SEAM (optional). Debug thread names.
std::string get_game_thread_name(const OSThread* /*t*/) { return "[Game]"; }
} // namespace mm::stub::threads

// ---------------------------------------------------------------------------
// The single supported game entry. rom_hash is XXH3-64 of the whole ROM
// (matches librecomp's check_hash); computed from baserom.us1.z64.
// Entry address 0x80000400 comes from RecompiledFuncs/lookup.cpp.
// ---------------------------------------------------------------------------
static std::vector<recomp::GameEntry> supported_games() {
    return {
        {
            .rom_hash = 0xECB515AE2C898E4FULL,
            .internal_name = "MISCHIEF MAKERS",
            .game_id = kGameId,
            .mod_game_id = "troublemakers",
            .save_type = mm_audio_input::save_type(), // Eep4k; evidence in PHASE2_NOTES_w4.md
            .is_enabled = true,
            .decompression_routine = nullptr,
            .has_compressed_code = false,
            .entrypoint_address = get_entrypoint_address(),
            .entrypoint = recomp_entrypoint,
            .on_init_callback = troublemakers::on_game_init,
        },
    };
}

static void exit_error(const char* str) {
    std::fprintf(stderr, "%s\n", str);
    std::exit(EXIT_FAILURE);
}

static void print_usage(const char* argv0) {
    std::fprintf(stderr,
        "usage: %s [rom.z64] [options]\n"
        "  run without a ROM argument to open the launcher (ROM select + options)\n"
        "  --fullscreen        borderless fullscreen (also toggles via RT64)\n"
        "  --window WxH        window size (default 1280x960); the scene renders\n"
        "                      at window-integer-scale, so bigger = sharper\n"
        "  --ssaa N            supersample N x on top of the window scale (1-8)\n"
        "  --msaa N            multisample antialiasing (2, 4, or 8)\n"
        "  --widescreen        expand the rendered field to the window aspect\n"
        "                      (opt-in: can reveal off-stage areas in a 2D game)\n"
        "  --no-widescreen     force the original 4:3 presentation\n"
        "options persist to ~/.config/troublemakers-recomp/display.cfg\n"
        "in game: F11 = fullscreen toggle, hold Tab = 3x fast-forward\n",
        argv0);
}

int main(int argc, char** argv) {
#if defined(__linux__)
    // Prefer SDL's native Wayland backend in Wayland sessions. SDL2 defaults
    // to X11, which runs through XWayland — and there the launcher's
    // accelerated SDL_Renderer creates a GLX context, which hard-fails with a
    // fatal X error (BadValue on X_GLXCreateContext) on some hybrid-GPU
    // setups even though the game itself renders with Vulkan. Done via the
    // env var rather than SDL_HINT_VIDEODRIVER because the hint only exists
    // since SDL 2.0.22 (Ubuntu 22.04 CI links 2.0.20); overwrite=0 keeps a
    // user-set SDL_VIDEODRIVER in charge.
    if (std::getenv("SDL_VIDEODRIVER") == nullptr &&
        std::getenv("WAYLAND_DISPLAY") != nullptr) {
        SDL_version v{};
        SDL_GetVersion(&v);
        // Comma-separated fallback lists parse only on SDL >= 2.24; older
        // SDL would read "wayland,x11" as one unknown driver and fail init.
        const bool driver_list_ok =
            SDL_VERSIONNUM(v.major, v.minor, v.patch) >= SDL_VERSIONNUM(2, 24, 0);
        setenv("SDL_VIDEODRIVER", driver_list_ok ? "wayland,x11" : "wayland", 0);
    }
#endif

    recomp::Version project_version{};
    if (!recomp::Version::from_string("0.2.0", project_version)) {
        exit_error("Invalid version string");
    }

    // Display options: config file first, CLI overrides, then persist the
    // resolved values so flags "stick" for the next flagless run.
    load_display_config();
    const char* rom_arg = nullptr;
    for (int i = 1; i < argc; i++) {
        std::string_view arg = argv[i];
        if (arg == "--fullscreen") {
            g_fullscreen = true;
        } else if (arg == "--widescreen") {
            g_widescreen = true;
        } else if (arg == "--no-widescreen") {
            g_widescreen = false;
        } else if (arg == "--window" && i + 1 < argc) {
            if (std::sscanf(argv[++i], "%dx%d", &g_window_w, &g_window_h) != 2 ||
                g_window_w < 320 || g_window_h < 240) {
                print_usage(argv[0]);
                exit_error("--window expects WxH, at least 320x240");
            }
        } else if (arg == "--ssaa" && i + 1 < argc) {
            g_ssaa = std::atoi(argv[++i]);
            if (g_ssaa < 1 || g_ssaa > 8) { print_usage(argv[0]); exit_error("--ssaa expects 1-8"); }
        } else if (arg == "--msaa" && i + 1 < argc) {
            g_msaa = std::atoi(argv[++i]);
            if (g_msaa != 2 && g_msaa != 4 && g_msaa != 8) { print_usage(argv[0]); exit_error("--msaa expects 2, 4 or 8"); }
        } else if (arg == "--help" || arg == "-h") {
            print_usage(argv[0]);
            return EXIT_SUCCESS;
        } else if (!arg.empty() && arg[0] != '-' && rom_arg == nullptr) {
            rom_arg = argv[i];
        } else {
            print_usage(argv[0]);
            exit_error("unknown option");
        }
    }

    // Store config (mods, saves) under a per-project folder in the user's
    // config dir. Sibling workers may relocate this.
    namespace fs = std::filesystem;
    fs::path config_dir = mm::get_app_folder_path();
    std::error_code ec;
    fs::create_directories(config_dir, ec);
    mm_audio_input::register_save_config(config_dir); // recomp::register_config_path
    mm_audio_input::init(); // SDL audio device + game-controller subsystem

    // Register the supported game + overlay/section tables.
    for (const auto& game : supported_games()) {
        recomp::register_game(game);
    }
    troublemakers::register_overlays();

    // If a ROM path was given, validate + load it now; the game auto-starts
    // from the first VI tick (see vi_callback).
    if (rom_arg != nullptr) {
        // select_rom validates the ROM against the registered GameEntry keyed
        // by game_id, so we must name the game we registered above.
        std::u8string game_id = kGameId;
        auto err = recomp::select_rom(fs::path(rom_arg), game_id);
        const char* msg = nullptr;
        switch (err) {
            case recomp::RomValidationError::Good: msg = "ROM validated and loaded."; break;
            case recomp::RomValidationError::FailedToOpen: msg = "ROM: failed to open."; break;
            case recomp::RomValidationError::NotARom: msg = "ROM: not a ROM."; break;
            case recomp::RomValidationError::IncorrectRom: msg = "ROM: incorrect ROM (hash mismatch)."; break;
            case recomp::RomValidationError::IncorrectVersion: msg = "ROM: incorrect version."; break;
            case recomp::RomValidationError::NotYet: msg = "ROM: not yet supported."; break;
            default: msg = "ROM: other error."; break;
        }
        std::fprintf(stdout, "[recomp] %s\n", msg);
        if (err != recomp::RomValidationError::Good) {
            return EXIT_FAILURE;
        }
        g_rom_path = reinterpret_cast<const char*>(
            fs::path(rom_arg).u8string().c_str()); // remember for the launcher
        g_rom_selected = true; // gfx_init_callback starts the game once gfx is up
    }
#ifdef MM_HAS_GRAPHICS
    else {
        // No ROM on the command line: show the splash screen (ROM select +
        // display options), like the other recomp projects' launchers. It
        // loads the ROM through the same recomp::select_rom path, so once it
        // returns StartGame the auto-start in vi_callback takes over.
        mm::launcher::DisplaySettings ds{g_window_w, g_window_h, g_fullscreen, g_widescreen};
        fs::path rom_path = fs::path(
            std::u8string(g_rom_path.begin(), g_rom_path.end()));
        auto outcome = mm::launcher::run(kGameId, project_version.to_string(), ds, rom_path);
        g_window_w = ds.window_w;
        g_window_h = ds.window_h;
        g_fullscreen = ds.fullscreen;
        g_widescreen = ds.widescreen;
        g_rom_path = reinterpret_cast<const char*>(rom_path.u8string().c_str());
        save_display_config(); // keep choices even if the user exits here
        if (outcome != mm::launcher::Outcome::StartGame) {
            return EXIT_SUCCESS;
        }
        g_rom_selected = true;
    }
#endif

    // Seed the renderer configuration before the runtime spawns the gfx
    // thread (the Rt64Context constructor reads it once at creation), and
    // persist the resolved options so they stick for the next run.
    apply_display_config();
    save_display_config();

    // Tell translated-code hooks to populate the extra tile columns and omit
    // the original 4:3 side-border strips. Explicit environment values still
    // win, which keeps each layer independently switchable for diagnostics.
    //
    // The hooks read std::getenv (the CRT environment). On Windows,
    // SDL_setenv writes the Win32 process environment, which the CRT
    // snapshot never sees — the values must go through _putenv_s instead
    // (overwrite=0 semantics preserved via the getenv check).
    auto set_env_default = [](const char* name, const char* value) {
#if defined(_WIN32)
        if (std::getenv(name) == nullptr) {
            _putenv_s(name, value);
        }
#else
        SDL_setenv(name, value, 0);
#endif
    };
    if (g_widescreen) {
        set_env_default("MM_WIDESCREEN_ACTIVE", "1");
        set_env_default("MM_BAND_WINGS", "1");
        set_env_default("MM_STATIC_WINGS", "1");
        set_env_default("MM_ENV_WINGS", "1");
        set_env_default("MM_MID_WINGS", "1");
    }

    // Build the runtime configuration. RSP + audio + input come from the
    // component libraries; renderer/gfx stay stubbed until src/graphics/ (RT64)
    // lands. rsp_callbacks and renderer_callbacks are mandatory (librecomp
    // asserts they are non-empty).
    recomp::rsp::callbacks_t rsp_callbacks = mm_rsp::make_callbacks();

    ultramodern::renderer::callbacks_t renderer_callbacks{
#ifdef MM_HAS_GRAPHICS
        .create_render_context = mm::graphics::create_render_context,
#else
        .create_render_context = mm::stub::renderer::create_render_context,
#endif
    };

    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = mm::stub::gfx::create_gfx,
        .create_window = mm::stub::gfx::create_window,
        .update_gfx = mm::stub::gfx::update_gfx,
    };

    ultramodern::audio_callbacks_t audio_callbacks = mm_audio_input::audio_callbacks();

    ultramodern::input::callbacks_t input_callbacks = mm_audio_input::input_callbacks();

    ultramodern::events::callbacks_t events_callbacks{
        .vi_callback = mm::stub::events::vi_callback,
        .gfx_init_callback = mm::stub::events::gfx_init_callback,
    };

    ultramodern::error_handling::callbacks_t error_handling_callbacks{
        .message_box = mm::stub::error::message_box,
    };

    ultramodern::threads::callbacks_t threads_callbacks{
        .get_game_thread_name = mm::stub::threads::get_game_thread_name,
    };

    recomp::Configuration cfg{
        .project_version = project_version,
        .window_handle = {}, // default -> create_window is called
        .rsp_callbacks = rsp_callbacks,
        .renderer_callbacks = renderer_callbacks,
        .audio_callbacks = audio_callbacks,
        .input_callbacks = input_callbacks,
        .gfx_callbacks = gfx_callbacks,
        .events_callbacks = events_callbacks,
        .error_handling_callbacks = error_handling_callbacks,
        .threads_callbacks = threads_callbacks,
        // requeue_sp = false restores the N64's lossy SP-event semantics. This
        // game produces three SP completions per frame (one gfx task + two
        // audio tasks) but its Sound code consumes only two from the size-1
        // gAudioTaskMessageQueue — on hardware the surplus interrupt message
        // is simply dropped. ultramodern's default (requeue until delivered)
        // instead accumulates one undeliverable token per frame in the
        // external-message queue, which livelocks the idle thread and starves
        // delivery of the one-shot DP-complete message: the game froze after
        // exactly three frames. See PHASE4_NOTES_a.md (driver appendix).
        .message_queue_control = { .requeue_sp = false },
    };

    // Blocks until the runtime quits (window close via update_gfx above, or
    // ultramodern::quit() from elsewhere).
    recomp::start(cfg);

    return EXIT_SUCCESS;
}
