// RSP callback glue for the Mischief Makers static recomp.
//
// The only RSP microcode this game ships that RSPRecomp can handle is the audio
// ucode `aspMain` (recompiled into generated/aspMain.cpp). Graphics RSP tasks
// run the gspFast3D (Fast3D) ucode, which is NOT statically recompiled — RT64
// interprets the display list via renderer_callbacks, exactly as Zelda64Recomp
// does for F3DEX. RSPRecomp's own source notes it targets "non-graphics"
// microcodes (it hardcodes DPC_STATUS reads to 0), so recompiling gspFast3D is
// neither needed nor viable. See PHASE2_NOTES_w2.md.
#include "mm_rsp.hpp"

#include <cstdio>

// Generated by RSPRecomp from aspMain.us1.rsp.toml. Signature matches
// RspUcodeFunc = RspExitReason(uint8_t* rdram, uint32_t ucode_addr).
extern RspUcodeFunc aspMain;

// TEMP DIAGNOSTIC (final verification): confirm every audio task exits with
// Broke. The ucode fetches its own command stream — its entry `jal 0x1150`
// IS the first-chunk prefetch, correctly resolved now that text_address is
// 0x04001080 (see aspMain.us1.rsp.toml and PHASE4_NOTES_a.md).
static RspExitReason aspMain_task(uint8_t* rdram, uint32_t ucode_addr) {
    static uint64_t n = 0, broke = 0;
    RspExitReason r = aspMain(rdram, ucode_addr);
    n++;
    if (r == RspExitReason::Broke) broke++;
    if (n <= 3 || n % 20 == 0) {
        fprintf(stderr, "[mm_rsp] aspMain %llu/%llu Broke\n",
            (unsigned long long)broke, (unsigned long long)n);
    }
    return r;
}

namespace mm_rsp {

// recomp::rsp::callbacks_t::get_rsp_microcode — return the recompiled ucode
// function for a given SP task, or nullptr if none applies.
static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
    case M_AUDTASK:
        // Audio task → the recompiled aspMain ucode.
        return aspMain_task;

    case M_GFXTASK:
        // Graphics task: handled by RT64 (renderer_callbacks), not by the RSP
        // recompiler. ultramodern's SP dispatch should not call
        // get_rsp_microcode for gfx tasks; if it ever does, surface it loudly
        // rather than silently dropping the frame.
        fprintf(stderr,
                "[mm_rsp] M_GFXTASK reached RSP dispatch — RT64 should have "
                "consumed it via renderer_callbacks\n");
        return nullptr;

    default:
        fprintf(stderr, "[mm_rsp] no ucode for task type %u\n",
                (unsigned)task->t.type);
        return nullptr;
    }
}

recomp::rsp::callbacks_t make_callbacks() {
    return recomp::rsp::callbacks_t{
        .get_rsp_microcode = get_rsp_microcode,
    };
}

void register_callbacks() {
    recomp::rsp::set_callbacks(make_callbacks());
    recomp::rsp::constants_init(); // prime rspReciprocals / rspInverseSquareRoots
}

} // namespace mm_rsp
